#!/bin/bash
#
# Run the Travis CI script that performs software testing and verification.
echo "Running pre-commit hook..."
source "$(git rev-parse --show-toplevel)"/scripts/travis/run-tests.sh > /dev/null
